# Simple package

name: OALT-DLAV
parent: default

#Video
matches:
  #Video
  - trigger: ":vimeolink"
    replace: ""
  #Audio
  - trigger: ":yournewalbum"
    replace: |
              Hi,

              Your new photo album is ready and uploaded at the link below,

              {{clipboard}}

              If there is anything further I can help with, please don't hesitate to let me know,

              Thanks,
    vars: 
      - name: "clipboard"
        type: "clipboard"
  #General
  - trigger: ":techcontact"
    replace: "It's best to contact Mitch Drake, our DLI Technician, \n You can reach them on 07 4631 2018 or at mitch.drake@usq.edu.au"
